---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"

- name: install chefdk debian apt packages
  apt:
    deb: "{{ chefdk_package_url }}"
    state: "{{ chefdk_package_state }}"
  become: yes
  when: ansible_distribution == 'Debian'

- name: install chefdk ubuntu apt packages
  apt:
    deb: "{{ chefdk_package_url }}"
    state: "{{ chefdk_package_state }}"
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: install chefdk yum packages
  yum:
    name: "{{ chefdk_package_url }}"
    state: "{{ chefdk_package_state }}"
  become: yes
  when: ansible_os_family == 'RedHat'
