---
- name: include variable overrides
  include_vars: "{{ item }}"
  vars:
    params:
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
      - "vars/{{ ansible_distribution | lower }}.yml"
      - "vars/{{ ansible_os_family | lower }}.yml"
      - "vars/default.yml"
  loop: "{{ q('first_found', params, skip=True) }}"

- name: install chefdk debian apt packages
  apt:
    deb: "{{ chefdk_package_url }}"
    state: "{{ chefdk_package_state }}"
  when: ansible_os_family == 'Debian'

- name: install chefdk yum packages
  yum:
    name: "{{ chefdk_package_url }}"
    state: "{{ chefdk_package_state }}"
  when: ansible_os_family == 'RedHat'
