---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos8
    image: centos:8
  - name: centos7
    image: centos:7
  - name: xenial
    image: ubuntu:xenial
  - name: bionic
    image: ubuntu:bionic
  - name: stretch
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
